steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/visitor-counter-api',
      '-f', 'Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/visitor-counter-api'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'visitor-counter-api',
      '--image', 'gcr.io/$PROJECT_ID/visitor-counter-api',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '8080'
    ]

options:
  logging: CLOUD_LOGGING_ONLY