steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/level-scheme-451514-m8/visitor-counter-api', '-f', 'visitor-counter-api/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/level-scheme-451514-m8/visitor-counter-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'visitor-counter-api',
        '--image', 'gcr.io/level-scheme-451514-m8/visitor-counter-api',
        '--platform', 'managed',
        '--region', 'europe-west4',
        '--allow-unauthenticated',
        '--port', '8080'
      ]
