options:
  logging: CLOUD_LOGGING_ONLY   
  # logs_bucket: gs://sarahbuild-bucket

serviceAccount: 'projects/level-scheme-451514-m8/serviceAccounts/cloudbuild-sa@level-scheme-451514-m8.iam.gserviceaccount.com'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t', 'gcr.io/level-scheme-451514-m8/visitor-counter-api','-f', 'visitor-counter-api/dockerfile', '.' ]


  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/level-scheme-451514-m8/visitor-counter-api']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'visitor-counter-api',
           '--image', 'gcr.io/level-scheme-451514-m8/visitor-counter-api',
           '--platform', 'managed',
           '--region', 'europe-west4',
           '--allow-unauthenticated',
           '--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/keys/firestore-key.json',
           '--port', '8080'   
           ]
