ARG PUBLIC_DIR

# Use the official Node.js 16 image
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy the rest of the application code
COPY . .

# Copy frontend from build argument
COPY ${PUBLIC_DIR} ./public

# Expose the port
EXPOSE 8080

# Start the application
CMD ["npm", "start"]