FROM node:18-slim

WORKDIR /app

# Copy package.json and package-lock.json from visitor-counter-api folder
COPY visitor-counter-api/package*.json ./

RUN npm install --omit=dev

# Copy server.js from visitor-counter-api folder
COPY visitor-counter-api/server.js ./

# Copy public folder (frontend) from root
COPY public/ ./public

EXPOSE 8080

CMD ["node", "server.js"]
