name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - master # Change to your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        project_id: level-scheme-451514-m8  # Replace with your Google Cloud project ID
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}  # Service Account JSON secret

    # Sync files to Google Cloud Storage
    - name: Install gsutil
      run: |
          echo "Installing Google Cloud SDK..."
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
    
    - name: List Files Before Deployment
      run: ls -R

    - name: Deploy to Google Cloud Storage
      run: |
        gsutil -m rsync -R ./public gs://sarahportfolio.cloud/


