name: Deploy to Cloud Run via Cloud Build

on:
  push:
    branches:
      - main  # Or "master" if that's your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: level-scheme-451514-m8
          export_default_credentials: true

      - name: Trigger Cloud Build
        run: |
          cd visitor-counter-api
          gcloud builds submit --config cloudbuild.yaml .
